"""second revision

Revision ID: 34cec3118bcb
Revises: d09bf32a3f6b
Create Date: 2023-10-30 00:46:35.315565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cec3118bcb'
down_revision: Union[str, None] = 'd09bf32a3f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dfgds', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rqre', sa.String(length=255), nullable=True),
    sa.Column('jhrh', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Test_description'), 'Test', ['description'], unique=False)
    op.create_index(op.f('ix_Test_dfgds'), 'Test', ['dfgds'], unique=False)
    op.create_index(op.f('ix_Test_id'), 'Test', ['id'], unique=False)
    op.create_index(op.f('ix_Test_jhrh'), 'Test', ['jhrh'], unique=False)
    op.create_index(op.f('ix_Test_rqre'), 'Test', ['rqre'], unique=False)
    op.add_column('items', sa.Column('new_test2', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_items_new_test2'), 'items', ['new_test2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_new_test2'), table_name='items')
    op.drop_column('items', 'new_test2')
    op.drop_index(op.f('ix_Test_rqre'), table_name='Test')
    op.drop_index(op.f('ix_Test_jhrh'), table_name='Test')
    op.drop_index(op.f('ix_Test_id'), table_name='Test')
    op.drop_index(op.f('ix_Test_dfgds'), table_name='Test')
    op.drop_index(op.f('ix_Test_description'), table_name='Test')
    op.drop_table('Test')
    # ### end Alembic commands ###
