"""newtest to item

Revision ID: d09bf32a3f6b
Revises: 
Create Date: 2023-10-30 00:41:54.224689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09bf32a3f6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('newtest', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_items_newtest'), 'items', ['newtest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_newtest'), table_name='items')
    op.drop_column('items', 'newtest')
    # ### end Alembic commands ###
